/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Sun-glasses.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sun-glasses.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.82, 3.66, 0]} rotation={[-Math.PI / 2, 0, -0.13]} scale={[0.67, 0.74, 0.67]}>
        <group position={[0, 3.95, 0]} scale={100}>
          <mesh geometry={nodes.Aviators_Black_gloss_0.geometry} material={materials.Black_gloss} />
          <mesh geometry={nodes.Aviators_Glass_tinted_0.geometry} material={materials.Glass_tinted} />
          <mesh geometry={nodes.Aviators_Gold_metallic_0.geometry} material={materials.Gold_metallic} />
          <mesh geometry={nodes.Aviators_Silver_metallic_0.geometry} material={materials.Silver_metallic} />
          <mesh geometry={nodes.Aviators_Transparent_0.geometry} material={materials.Transparent} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Sun-glasses.glb')
