/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rigged-hand.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Rigged-hand.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.pulseR} />
          <primitive object={nodes.index_tipR} />
          <primitive object={nodes.middle_tipR} />
          <primitive object={nodes.ring_tipR} />
          <primitive object={nodes.pinky_tipR} />
          <primitive object={nodes.thumb_tipR} />
          <skinnedMesh name="handSmooth001" geometry={nodes.handSmooth001.geometry} material={materials.lambert1} skeleton={nodes.handSmooth001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Rigged-hand.glb')
